{
 "title": "Energy usage",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Electricity used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "format": "kwatth",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "from(bucket: \"energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"electricity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"consumption\")\r\n  |> keep(columns:[\"_value\"])\r\n  |> sum()",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Go cost (units only)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 },
   "format": "currencyGBP",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "from(bucket: \"energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"electricity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cost\")\r\n  |> keep(columns:[\"_value\"])\r\n  |> sum()\r\n  |> map(fn: (r) => ({\r\n      _value: r._value / 100.0\r\n    })\r\n  )",
     "select": [
      [
       { "params": [ "cost" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Go cost (total)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 0 },
   "format": "currencyGBP",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "from(bucket: \"energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"electricity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"total_cost\")\r\n  |> keep(columns:[\"_value\"])\r\n  |> sum()\r\n  |> map(fn: (r) => ({\r\n      _value: r._value / 100.0\r\n    })\r\n  )",
     "select": [
      [
       { "params": [ "cost" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Go effective unit cost",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "format": "currencyGBP",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "consumption = from(bucket: \"energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"electricity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"consumption\")\r\n  |> keep(columns:[\"_start\",\"_value\"])\r\n  |> sum()\r\n\r\ncost = from(bucket: \"energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"electricity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"total_cost\")\r\n  |> keep(columns:[\"_start\",\"_value\"])\r\n  |> sum()\r\n\r\njoin(tables: {cost: cost, consumption: consumption}, on: [\"_start\"])\r\n  |> map(fn: (r) => ({_value: (r._value_cost / r._value_consumption) / 100.0 }))",
     "select": [
      [
       { "params": [ "cost" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tracker cost (units only)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 2 },
   "format": "currencyGBP",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "from(bucket: \"energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"electricity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"tracker_cost\")\r\n  |> keep(columns:[\"_value\"])\r\n  |> sum()\r\n  |> map(fn: (r) => ({\r\n      _value: r._value / 100.0\r\n    })\r\n  )",
     "select": [
      [
       { "params": [ "cost" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tracker cost (total)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 2 },
   "format": "currencyGBP",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "from(bucket: \"energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"electricity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"tracker_total_cost\")\r\n  |> keep(columns:[\"_value\"])\r\n  |> sum()\r\n  |> map(fn: (r) => ({\r\n      _value: r._value / 100.0\r\n    })\r\n  )",
     "select": [
      [
       { "params": [ "cost" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tracker effective unit cost",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 2 },
   "format": "currencyGBP",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "consumption = from(bucket: \"energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"electricity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"consumption\")\r\n  |> keep(columns:[\"_start\",\"_value\"])\r\n  |> sum()\r\n\r\ncost = from(bucket: \"energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"electricity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"tracker_total_cost\")\r\n  |> keep(columns:[\"_start\",\"_value\"])\r\n  |> sum()\r\n\r\njoin(tables: {cost: cost, consumption: consumption}, on: [\"_start\"])\r\n  |> map(fn: (r) => ({_value: (r._value_cost / r._value_consumption) / 100.0 }))",
     "select": [
      [
       { "params": [ "cost" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Agile cost (units only)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 4 },
   "format": "currencyGBP",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "from(bucket: \"energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"electricity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"agile_cost\")\r\n  |> keep(columns:[\"_value\"])\r\n  |> sum()\r\n  |> map(fn: (r) => ({\r\n      _value: r._value / 100.0\r\n    })\r\n  )",
     "select": [
      [
       { "params": [ "cost" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Agile cost (total)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 4 },
   "format": "currencyGBP",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "from(bucket: \"energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"electricity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"agile_total_cost\")\r\n  |> keep(columns:[\"_value\"])\r\n  |> sum()\r\n  |> map(fn: (r) => ({\r\n      _value: r._value / 100.0\r\n    })\r\n  )",
     "select": [
      [
       { "params": [ "cost" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Agile effective unit cost",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 4 },
   "format": "currencyGBP",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "consumption = from(bucket: \"energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"electricity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"consumption\")\r\n  |> keep(columns:[\"_start\",\"_value\"])\r\n  |> sum()\r\n\r\ncost = from(bucket: \"energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"electricity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"agile_total_cost\")\r\n  |> keep(columns:[\"_start\",\"_value\"])\r\n  |> sum()\r\n\r\njoin(tables: {cost: cost, consumption: consumption}, on: [\"_start\"])\r\n  |> map(fn: (r) => ({_value: (r._value_cost / r._value_consumption) / 100.0 }))",
     "select": [
      [
       { "params": [ "cost" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Electricity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "kwatth", "label": "Usage" }
   ],
   "targets": [
    {
     "alias": "Usage",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "from(bucket: \"energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"electricity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"consumption\")\r\n  |> keep(columns:[\"_value\", \"_time\", \"_field\"])\r\n  |> aggregateWindow(every: 30m, fn: mean)",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Go cost",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "from(bucket: \"energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"electricity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"agile_cost\" or r[\"_field\"] == \"cost\" or r[\"_field\"] == \"tracker_cost\")\r\n  |> keep(columns:[\"_value\", \"_time\", \"_field\"])\r\n  |> map(fn: (r) => ({\r\n      _value: r._value / 100.0,\r\n      _time: r._time,\r\n      _field: r._field\r\n    })\r\n  )\r\n  |> aggregateWindow(every: 30m, fn: mean)",
     "select": [
      [
       { "params": [ "cost" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gas used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 14 },
   "format": "kwatth",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "gas",
     "query": "from(bucket: \"energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gas\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"consumption\")\r\n  |> keep(columns:[\"_value\"])\r\n  |> sum()",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gas cost (units only)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 14 },
   "format": "currencyGBP",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "from(bucket: \"energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gas\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cost\")\r\n  |> keep(columns:[\"_value\"])\r\n  |> sum()\r\n  |> map(fn: (r) => ({\r\n      _value: r._value / 100.0\r\n    })\r\n  )",
     "select": [
      [
       { "params": [ "cost" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gas cost (total)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 14 },
   "format": "currencyGBP",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "from(bucket: \"energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gas\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"total_cost\")\r\n  |> keep(columns:[\"_value\"])\r\n  |> sum()\r\n  |> map(fn: (r) => ({\r\n      _value: r._value / 100.0\r\n    })\r\n  )",
     "select": [
      [
       { "params": [ "cost" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gas effective unit cost",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 14 },
   "format": "currencyGBP",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "consumption = from(bucket: \"energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"electricity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"consumption\")\r\n  |> keep(columns:[\"_start\",\"_value\"])\r\n  |> sum()\r\n\r\ncost = from(bucket: \"energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gas\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"total_cost\")\r\n  |> keep(columns:[\"_start\",\"_value\"])\r\n  |> sum()\r\n\r\njoin(tables: {cost: cost, consumption: consumption}, on: [\"_start\"])\r\n  |> map(fn: (r) => ({_value: (r._value_cost / r._value_consumption) / 100.0 }))",
     "select": [
      [
       { "params": [ "cost" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "kwatth", "label": "Usage" }
   ],
   "targets": [
    {
     "alias": "Usage",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "gas",
     "query": "from(bucket: \"energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gas\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"consumption\")\r\n  |> keep(columns:[\"_value\", \"_time\", \"_field\"])\r\n  |> aggregateWindow(every: 30m, fn: mean)",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Cost",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "from(bucket: \"energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gas\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cost\")\r\n  |> keep(columns:[\"_value\", \"_time\", \"_field\"])\r\n  |> map(fn: (r) => ({\r\n      _value: r._value / 100.0,\r\n      _time: r._time,\r\n      _field: r._field\r\n    })\r\n  )\r\n  |> aggregateWindow(every: 30m, fn: mean)",
     "select": [
      [
       { "params": [ "cost" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}